exports.data = [
  {
    programId: '1',
    date: '2022-02-24 09:54:05',
    user: 'loso kim',
    program: 'Booking Creation',
    programUI: 'ESM_BKG_0079',
    fileName: 'opus_video1.mp4',
    src: 'https://www.youtube.com/embed/3xccmeAsy8g',
    title: '1. How to create a new Booking',
    description: '',
    processMap: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    ratingScore: '3.5',
    vote: '12',
    resp: '9'

  },
  {
    programId: '2',
    date: '2022-02-24 09:54:05',
    user: 'loso kim',
    program: 'Booking Creation',
    programUI: 'ESM_BKG_0079',
    fileName: 'opus_video2.mp4',
    src: 'https://www.youtube.com/embed/BwZs3H_UN3k',
    title: '2. How to issue a new B/L',
    description: 'In case dagerous cargo, please check whether company acceppt thoes',
    processMap: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    ratingScore: '4.0',
    vote: '12',
    resp: '9'

  },
  { programId: '3',
    date: '2022-02-24 09:54:05',
    user: 'loso kim',
    program: 'Booking Creation',
    programUI: 'ESM_BKG_0079',
    fileName: 'opus_video3.mp4',
    src: 'https://www.youtube.com/embed/YaykGT215b4',
    title: '3. How to revise a Booking',
    description: 'In case dagerous cargo, please check whether company acceppt thoes',
    processMap: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    ratingScore: '2.0',
    vote: '12',
    resp: '9'

  },
  { programId: '4',
    date: '2022-02-24 09:54:05',
    user: 'loso kim',
    program: 'Booking Creation',
    programUI: 'ESM_BKG_0079',
    fileName: 'opus_video4.mp4',
    src: 'https://drive.google.com/file/d/1K8lr7u5q4iUQnfPnCvMy_rHfgpk_eaj_/preview',
    title: '4. How to split a Booking',
    description: 'In case dagerous cargo, please check whether company acceppt thoes',
    processMap: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    ratingScore: '3.5',
    vote: '12',
    resp: '9'

  },
  { programId: 5,
    date: '2022-02-24 09:54:05',
    user: 'loso kim',
    program: 'Booking Creation',
    programUI: 'ESM_BKG_0079',
    fileName: 'opus_video5.mp4',
    src: 'https://www.youtube.com/embed/UVbv-PJXm14',
    title: '5. How to merge a Booking',
    description: 'In case dagerous cargo, please check whether company acceppt thoes',
    processMap: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    ratingScore: '4.0',
    vote: '12',
    resp: '9'

  },
  { programId: '6',
    date: '2022-02-24 09:54:05',
    user: 'loso kim',
    program: 'Booking Creation',
    programUI: 'ESM_BKG_0079',
    fileName: 'opus_video6.mp4',
    src: 'https://www.youtube.com/embed/UVbv-PJXm14',
    title: '6. How to cancel a Booking',
    description: 'In case dagerous cargo, please check whether company acceppt thoes',
    processMap: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    ratingScore: '4.0',
    vote: '12',
    resp: '9'

  }
]
